apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: # Here past result encoding values
  mongo-password: # Here PAst result enconding value password
  


# This command for encoding: echo -n mongouser | base64 